//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella_de_Carbono.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class informes
    {
        public int idInformes { get; set; }
        public double sumatoria { get; set; }
        public double promedio { get; set; }
        public int cantidad { get; set; }
    }


    public partial class informes
    {
        public int otero { get; set; }
        public int otero2 { get; set; }
        public int otero3 { get; set; }

    }
}
