//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huella_de_Carbono.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuelladeCarbonoEntities1 : DbContext
    {
        public HuelladeCarbonoEntities1()
            : base("name=HuelladeCarbonoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entidad> entidad { get; set; }
        public virtual DbSet<informes> informes { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
